spring:
  application:
    name: backend-user
  datasource:
    url: jdbc:postgresql://${DB_HOST:lasteamcity.ddns.net}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Gp9#q2Wz!mR6*xK4}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 151
      minimum-idle: 5
  jpa:
    hibernate:
      # 开发环境可以用 update，生产环境强烈建议用 validate 并配合 Flyway/Liquibase
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:lasteamcity.ddns.net}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:las} # 如果没有密码留空
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
springdoc:
  swagger-ui:
    # swagger-ui.html 位置
    path: /api-docs.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
remote:
  ws:
    url: ws://103.40.14.23:57211
    token: '@LazyAlienServer'
server:
  port: 8081
secret:
  jwt:
    key: 'c(<sJM3RMjpv-RV?6Z&TV]a7SRMe3AKC>ajZTT,WTUyPWJ@+vfYn"Af85-4j!Fa2HV&CSxxR+MX|B@vyAfCJ|2uce.R+s)?2cGA<C&7Q;N]%t<(RS!A:%V2v[G:"W)U-8[k-Wa|s"Uxf,*SfbUQ#NFvY%?Wd5:|man!3U>h2bKXr7>?kT%h?S6D(*]MaPvZ.m]TERR#@6#rp,U@m:2:cHWkxt&rBAHvtE>=Ket&f55Cs(RWTY-_"+A;*[Ge*xYx?'

